# Generated by Django 3.0.9 on 2020-11-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zorg',
            name='profile_photo',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='assets/zorg/profile_photo/'),
        ),
    ]
