# Generated by Django 3.1.1 on 2020-11-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zorg',
            name='id',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
