# Generated by Django 3.0.9 on 2020-11-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zorg',
            name='unique_id',
            field=models.EmailField(default='saampel@cara.com', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
