# Generated by Django 3.1.1 on 2020-11-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0004_auto_20201116_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='Images/')),
                ('field', models.FileField(blank=True, max_length=200, null=True, upload_to='files/')),
            ],
        ),
    ]
