# Generated by Django 3.1.1 on 2020-11-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0005_samplemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplemodel',
            old_name='field',
            new_name='file',
        ),
    ]
