# Generated by Django 3.0.9 on 2020-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0007_auto_20201116_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplemodel',
            name='file',
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
