# Generated by Django 3.0.9 on 2020-11-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0008_auto_20201118_0226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleModel',
        ),
        migrations.AlterField(
            model_name='zorg',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
