# Generated by Django 3.0.9 on 2020-11-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0009_auto_20201118_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='zorg',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/zorgz_images/'),
        ),
        migrations.AddField(
            model_name='zorg',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/zorgz_images/'),
        ),
        migrations.AddField(
            model_name='zorg',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/zorgz_images/'),
        ),
        migrations.AddField(
            model_name='zorg',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/zorgz_images/'),
        ),
    ]
