# Generated by Django 3.0.9 on 2020-11-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0010_auto_20201118_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='zorg',
            name='cover_photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/cover_photo/'),
        ),
        migrations.AlterField(
            model_name='zorg',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/zorg_images/'),
        ),
        migrations.AlterField(
            model_name='zorg',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/zorg_images/'),
        ),
        migrations.AlterField(
            model_name='zorg',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/zorg_images/'),
        ),
        migrations.AlterField(
            model_name='zorg',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/zorg_images/'),
        ),
    ]
