# Generated by Django 3.0.9 on 2020-08-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
