# Generated by Django 3.0.9 on 2020-10-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
