# Generated by Django 3.0.9 on 2020-08-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='totaltime',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
