# Generated by Django 3.0.9 on 2020-09-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='zorg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.Zorg'),
        ),
    ]
