# Generated by Django 3.1.1 on 2020-09-23 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200924_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='zorg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zorg', to='api.zorg'),
        ),
    ]
