# Generated by Django 3.1.1 on 2020-09-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200924_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='zorg',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.categories'),
        ),
    ]
