# Generated by Django 3.1.1 on 2020-09-24 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200924_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zorg_branche',
            name='zorg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.zorg'),
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
