# Generated by Django 3.1.1 on 2020-09-25 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200925_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetail',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='appointmentdetail',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='appointmentdetail',
            name='servicePrice',
        ),
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.zorg_branche'),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='api.appointment'),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.categories'),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='api.service'),
        ),
    ]
