# Generated by Django 3.1.1 on 2020-09-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200925_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='total_price',
        ),
    ]
