# Generated by Django 3.1.1 on 2020-09-25 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200925_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetail',
            name='appointment',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
