# Generated by Django 3.1.1 on 2020-09-25 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200925_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.zorg_branche'),
        ),
    ]
