# Generated by Django 3.1.1 on 2020-09-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_appointment_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetail',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='api.appointment'),
        ),
    ]
